name: sociopataorg

services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "3010:80"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sociopata.rule=Host(`sociopata.org.local`)"
      - "traefik.http.routers.sociopata.entrypoints=websecure"
      - "traefik.http.routers.sociopata.tls=true"
      - "traefik.http.services.sociopata.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
